### Cadastrar mais um Barbeiro
POST http://localhost:8080/barbeiros
Content-Type: application/json

{
  "nome": "Arthur Machado",
  "email": "arthur@barbearia.com",
  "telefone": "98999999999",
  "especialidade": "Tesoura e Clássicos",
  "percentualComissao": 35.0
}

###

### Cadastrar mais um Corte
POST http://localhost:8080/servicos
Content-Type: application/json

{
  "nome": "Barba Terapia",
  "preco": 35.0,
  "tempoEstimadoMinutos": 30
}